"""Convert a project's CLAUDE.md into memory entries.

Two independent operations:
  - import: parse CLAUDE.md, split it into categorized memory entries.
  - stub-rewrite: replace CLAUDE.md with a slim pointer at Memory MCP (the
    original is backed up). Only meaningful for Claude Code, which reads
    CLAUDE.md; harmless otherwise.
"""

import re
import shutil
from pathlib import Path

from memory_mcp.models import RULE_CATEGORIES, MemoryCategory, StoreMemoryRequest
from memory_mcp.services.memory_service import MemoryService

_HEADING = re.compile(r"^(#{1,6})\s+(.*)")
_BULLET = re.compile(r"^\s*(?:[-*+]|\d+[.)])\s+(.*)")

# Heading-keyword -> category. Forbidden is checked before mandatory so a
# heading like "Never do this" maps to forbidden rather than mandatory.
_CATEGORY_KEYWORDS = [
    (MemoryCategory.FORBIDDEN_RULES, ["forbidden", "never", "don't", "do not", "avoid", "prohibit"]),
    (MemoryCategory.MANDATORY_RULES, ["mandatory", "must", "always", "rule", "required", "convention", "guideline"]),
    (MemoryCategory.ARCHITECTURE, ["architecture", "structure", "design", "stack", "module", "component"]),
    (MemoryCategory.DEVOPS, ["devops", "deploy", "ci/cd", "pipeline", "infra", "build", "release"]),
    (MemoryCategory.DECISION, ["decision", "chose", "rationale", "why we"]),
    (MemoryCategory.SPRINT, ["sprint", "milestone", "roadmap", "backlog"]),
    (MemoryCategory.REFERENCE, ["reference", "resource", "link", "external"]),
]

_STUB_TEMPLATE = """\
# Project Memory

This project's rules, decisions, architecture notes, and context are stored in
the **Memory MCP** server under project `{project}` - not in this file.

At the start of every session:
- Call `memory_session_start("{project}")` to load mandatory rules, forbidden
  rules, the last session summary, sprint goals, and recent decisions.
- Treat the returned mandatory/forbidden rules as binding.

During work, store new decisions and rules with `memory_store(...)`.
Before finishing, call `memory_session_end(...)` with a summary.

> Generated by `memory_import_claude_md`. The original CLAUDE.md was saved
> next to this file with a `.imported-bak` suffix.
"""


def _category_for(heading: str) -> MemoryCategory:
    h = heading.lower()
    for category, keywords in _CATEGORY_KEYWORDS:
        if any(k in h for k in keywords):
            return category
    return MemoryCategory.DEVELOPER_DOCS


def _parse_sections(text: str) -> list[tuple[str, str]]:
    """Split markdown into (heading, body) sections on every heading line."""
    sections: list[tuple[str, str]] = []
    heading: str | None = None
    body: list[str] = []

    def flush() -> None:
        joined = "\n".join(body).strip()
        if heading is not None:
            sections.append((heading, joined))
        elif joined:
            sections.append(("Overview", joined))

    for line in text.splitlines():
        m = _HEADING.match(line)
        if m:
            flush()
            heading = m.group(2).strip()
            body = []
        else:
            body.append(line)
    flush()
    return sections


def _bullets(body: str) -> list[str]:
    items = []
    for line in body.splitlines():
        m = _BULLET.match(line)
        if m and m.group(1).strip():
            items.append(m.group(1).strip())
    return items


def _title_from(text: str, limit: int = 90) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 3] + "..."


class ClaudeMdService:
    """Imports CLAUDE.md content into memory; optionally stubs out the file."""

    def __init__(self, memory_service: MemoryService):
        self._memory_service = memory_service

    def import_file(self, project: str, path: str, stub_rewrite: bool = False) -> dict:
        md_path = Path(path).expanduser()
        if md_path.is_dir():
            md_path = md_path / "CLAUDE.md"
        if not md_path.is_file():
            raise ValueError(f"CLAUDE.md not found at: {md_path}")

        text = md_path.read_text(encoding="utf-8")
        created: list[dict] = []

        for heading, body in _parse_sections(text):
            if not body:
                continue
            category = _category_for(heading)

            # Rule sections: store each bullet as its own rule so enforcement
            # can reference them individually.
            if category in RULE_CATEGORIES:
                items = _bullets(body)
                if items:
                    for item in items:
                        created.append(self._store(project, category, _title_from(item), item))
                    continue

            created.append(self._store(project, category, _title_from(heading), body))

        result: dict = {
            "status": "ok",
            "source": str(md_path),
            "imported": len(created),
            "memories": created,
        }
        if stub_rewrite:
            result["stub"] = self._write_stub(md_path, project)
        return result

    def _store(self, project: str, category: MemoryCategory, title: str, content: str) -> dict:
        memory = self._memory_service.store(
            StoreMemoryRequest(
                project=project, category=category, title=title or "Untitled",
                content=content, source="claude_md", tags=["imported", "claude-md"],
            )
        )
        return {"id": memory.id, "category": category.value, "title": memory.title}

    def _write_stub(self, md_path: Path, project: str) -> dict:
        backup = md_path.with_name(md_path.stem + ".imported-bak.md")
        n = 1
        while backup.exists():
            backup = md_path.with_name(f"{md_path.stem}.imported-bak.{n}.md")
            n += 1
        shutil.copy2(md_path, backup)
        md_path.write_text(_STUB_TEMPLATE.format(project=project), encoding="utf-8")
        return {"rewrote": str(md_path), "backup": str(backup)}
